
package ru.gretchen.accountant.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrackedChatIdService", targetNamespace = "http://Service.soap.ramz.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrackedChatIdService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ru.gretchen.accountant.soap.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service.soap.ramz.com/TrackedChatIdService/takeTrackedListRequest", output = "http://Service.soap.ramz.com/TrackedChatIdService/takeTrackedListResponse")
    public ArrayList takeTrackedList(
        @WebParam(name = "arg0", partName = "arg0")
                String arg0);

}
